# Generated by Django 3.2.5 on 2022-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=100, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='曲名')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('titles', models.ManyToManyField(to='web.Score')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.TextField(blank=True, max_length=1000, verbose_name='メモ')),
                ('posteddate', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('titles', models.ManyToManyField(to='web.Score')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mediatype', models.CharField(max_length=50, verbose_name='種類')),
                ('mediapath', models.CharField(max_length=10000, verbose_name='メディアパス')),
                ('uploaddate', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('titles', models.ManyToManyField(to='web.Score')),
            ],
        ),
    ]
